services:
  backend:
    image: movingju/public:pigo_rec
    ports:
      - "8080:8080"
    environment:
      - UVICORN_RELOAD=true
    tty: true
    networks:
      - server-net

networks:
  server-net: