services:
  backend:
    build: .
    ports:
      - "80:8000"
    environment:
      - UVICORN_RELOAD=true
    volumes:
      - .:/app
      - /app/.venv
    tty: true
    networks:
      - server-net

networks:
  server-net: