[project]
name = "pick-and-go"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.17"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.14",
    "mysql-connector-python>=9.3.0",
    "uvicorn>=0.35.0",
]
